FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install -g nodemon

EXPOSE 3000

CMD ["nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "npm", "run", "start:dev"] 