FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm install -g nodemon ts-node

EXPOSE 3000

CMD ["nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "ts-node", "src/telegram/transactionBot/bot.ts"] 